"""empty message

Revision ID: 66de33263a27
Revises: 870977c4985d
Create Date: 2024-09-29 18:39:17.124509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66de33263a27'
down_revision: Union[str, None] = '870977c4985d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_rank'), 'tasks', ['rank'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_rank'), table_name='tasks')
    # ### end Alembic commands ###
