"""empty message

Revision ID: 870977c4985d
Revises: 3a0e149e1ab6
Create Date: 2024-09-29 12:42:48.096006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870977c4985d'
down_revision: Union[str, None] = '3a0e149e1ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_order'), 'tasks', ['order'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_order'), table_name='tasks')
    # ### end Alembic commands ###
